remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Unsupervised feature classification in STM images]
description: [A blog site describing my summer research project at the London Centre for Nanotechnology supervised by Prof Steven Schofield.]
